# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    expose:
      - 5433

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080